# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Spencer/Documents/Vivado/pipelined-zanpu/pipelined-zanpu.srcs/sources_1/ip/instruction_mem/instruction_mem.xci
# IP: The module: 'instruction_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Spencer/Documents/Vivado/pipelined-zanpu/pipelined-zanpu.srcs/sources_1/ip/instruction_mem/instruction_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'instruction_mem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/Spencer/Documents/Vivado/pipelined-zanpu/pipelined-zanpu.srcs/sources_1/ip/instruction_mem/instruction_mem.xci
# IP: The module: 'instruction_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Spencer/Documents/Vivado/pipelined-zanpu/pipelined-zanpu.srcs/sources_1/ip/instruction_mem/instruction_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'instruction_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
